name: Check

on: [pull_request]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check pull request description
    - run: echo "There is no pull request description"
      if: github.event.pull_request.body == ""
    
    - run: echo "There is a pull pull request description"
      if: github.event.pull_request.body != ""
 
    
