name: Check
on:
 pull_request
jobs:
  example:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Run actions/checkout 
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run fabiankoestring/body-regex-validator-action
      uses: fabiankoestring/body-regex-validator-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_PATTERN: '^(.*Description.*Changes.*Tests.*)$'
