name: Check

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.pull_request.body == ""
        issue-message: 'Please include a description for your Pull Request'

